name: audit-check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  audit-check:
    permissions:
      contents: read
    uses: muleyuck/github-actions/.github/workflows/audit-node-pnpm.yml@v1
