name: unit-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  unit-test:
    permissions:
      contents: read
    uses: muleyuck/github-actions/.github/workflows/ci-node-pnpm.yml@v1
